# migrations/versions/4f1f4690424a_added_teacher_model_and_relationship_to_.py
"""Added Teacher model and relationship to Student

Revision ID: 4f1f4690424a
Revises: f9c217dece91
Create Date: 2025-11-20 16:41:40.818852

"""
from alembic import op # type: ignore
import sqlalchemy as sa # type: ignore


# revision identifiers, used by Alembic.
revision = '4f1f4690424a'
down_revision = 'f9c217dece91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
